import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import { SnakeGrid } from "../components/SnakeGrid";

const Home: NextPage = () => {
    const [currentUrl, setCurrentUrl] = useState<string>('');

    useEffect(() => {
        // Only runs on client side after mount
        setCurrentUrl(window.location.origin);
        console.log('NEXTAUTH_URL:', process.env.NEXT_PUBLIC_NEXTAUTH_URL);
        console.log('Current window location:', window.location.origin);
        console.log('Node ENV:', process.env.NODE_ENV);
    }, []);

    return (
        <div className="">
            <Head>
                <title>RainbowKit App</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <main className="bg-gradient-to-br flex flex-col w-full items-center from-slate-900 to-slate-800 h-screen">
                <ConnectButton />

                {/* Debug Info - Remove this after fixing */}
                {currentUrl && (
                    <div className="bg-yellow-100 text-black p-4 rounded mt-4 text-sm max-w-2xl">
                        <h3 className="font-bold mb-2">🐛 Debug Info:</h3>
                        <p><strong>Window Origin:</strong> {currentUrl}</p>
                        <p><strong>Public Env Var:</strong> {process.env.NEXT_PUBLIC_NEXTAUTH_URL || 'Not set'}</p>
                        <p><strong>Env Var:</strong> {process.env.NEXTAUTH_URL || 'Not set'}</p>
                        <p><strong>Environment:</strong> {process.env.NODE_ENV}</p>
                    </div>
                )}
                <SnakeGrid />
            </main>

            <footer className="">

            </footer>
        </div>
    );
};

export default Home;