import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import {SnakeGrid} from "../components/SnakeGrid";


const Home: NextPage = () => {

  return (
    <div className="">
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="bg-gradient-to-br flex flex-col w-full items-center from-slate-900 to-slate-800 h-screen">




          <ConnectButton/>


          <SnakeGrid/>
      </main>

      <footer className="">

      </footer>
    </div>
  );
};

export default Home;
